[window]
decorations = "None"
option_as_alt = "Both" # macOS only
padding = { x = 4, y = 4 }
dynamic_padding = true

[font]
size = 11
offset = {y = 2}
normal = { family = "Berkeley Mono", style = "Regular" } 
bold = { family = "Berkeley Mono", style = "Bold" } 
bold_italic = { family = "Berkeley Mono", style = "Bold Italic" } 
italic = { family = "Berkeley Mono", style = "Regular" } 
